FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]

# docker build -f Dockerfile.dev .
# docker run -p 3000:3000 -v /app/node_module -v $(pwd):/app 